In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.2)

In [3]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\chait\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [4]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9805555555555555

In [5]:
rf = RandomForestClassifier(n_estimators = 40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.95

In [6]:
# we saw here the problem with train_test_split that you can't run the model one time and tell that this performance is better.
# you have to run this model multiple times.
# now firstly we use k-fold API to demonstrate what exactly it is doing 
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
def getscore(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [9]:
getscore(SVC(),x_train,x_test,y_train,y_test)

0.9805555555555555

In [10]:
scores_l=[]
scores_svm = []
scores_rf = []
for train_index , test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test =digits.data[train_index],digits.data[test_index],digits.target[train_index],\
    digits.target[test_index]
    scores_l.append(getscore(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_svm.append(getscore(SVC(),x_train,x_test,y_train,y_test))
    scores_rf.append(getscore(RandomForestClassifier(n_estimators=50),x_train,x_test,y_train,y_test))

C:\Users\chait\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\chait\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [11]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [12]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [13]:
scores_rf

[0.9348914858096828, 0.9565943238731218, 0.9348914858096828]

In [14]:
# upto this we wrote this code to learn how exactly the kfold works but this is not exactly how we write code for it.
# we already have a method exist for this code i.e cross_val_code
from sklearn.model_selection import cross_val_score 
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\chait\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\chait\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [15]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [16]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.93888889, 0.9       , 0.96100279, 0.9637883 , 0.93314763])

In [18]:
# then after words u can do parametric tuning and take out the best performance from the model
cross_val_score(RandomForestClassifier(n_estimators=60),digits.data,digits.target)

array([0.93333333, 0.90277778, 0.95821727, 0.9637883 , 0.92479109])

In [ ]:
# we seen that cross validation technique is very useful , it not only allows us to compare different algorithms 
# but the same algorithms with different parameters how it would behave for a given problem