In [1]:
import numpy as np

In [2]:
myarr = np.array([3,6,37,7],np.int64)

In [3]:
myarr

array([ 3,  6, 37,  7], dtype=int64)

In [4]:
myarr[0]

3

In [5]:
# if we make 2-d array
myarr1 = np.array([[3,6,37,7]],np.int64)
myarr1

array([[ 3,  6, 37,  7]], dtype=int64)

In [6]:
myarr1[0,1]

6

In [7]:
myarr1.shape

(1, 4)

In [8]:
myarr.dtype

dtype('int64')

In [9]:
myarr1[0,1]=45
myarr1

array([[ 3, 45, 37,  7]], dtype=int64)

** Array creation : conversion from other python structures**

In [10]:
listarray = np.array([[1,2,3],[5,7,5],[7,8,9]])
listarray

array([[1, 2, 3],
       [5, 7, 5],
       [7, 8, 9]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
np.array({9,33,35})

array({9, 35, 33}, dtype=object)

In [15]:
zero = np.zeros((2,5))
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zero.shape

(2, 5)

In [17]:
zero.size

10

In [18]:
zero.dtype

dtype('float64')

In [19]:
# A arange function gives you output as a numpy array
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
#linspace function gives the equally linearly spaced elements between two numbers.
lspace = np.linspace(1,50,10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [21]:
lspace1 = np.linspace(1,4,4)
lspace1

array([1., 2., 3., 4.])

In [22]:
# empty function gives us some random empty array filled with some random elements , and later we can update that elements with required one.
emp = np.empty((4,6))
emp

array([[7.13166964e-312, 7.70742408e-322, 0.00000000e+000,
        0.00000000e+000, 1.37961302e-306, 1.16095484e-028],
       [4.82679020e+233, 9.19596581e+170, 2.49970345e+262,
        1.32882766e+179, 6.93256904e+212, 3.03388837e-152],
       [1.32850729e+179, 2.32160957e-152, 1.81363454e-152,
        1.35712977e+166, 9.93939663e+247, 2.93494585e+222],
       [2.31284990e+161, 7.58792319e-096, 4.82486827e+233,
        1.46899930e+179, 9.08367237e+223, 1.16466228e-028]])

In [23]:
# empty functions are used in finding efficiencies.
emp_like =np.empty_like(lspace)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [24]:
# Identity matrix -
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [25]:
ide.shape

(45, 45)

In [26]:
# Reshape 
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
np.arange(99).reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [30]:
# to make any dimentional array to straight 1-d array then we can use ravel function.
arr = arr.ravel()

In [31]:
arr.shape

(99,)

In [32]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [33]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [34]:
ar.sum(axis=0)

array([12,  8,  9])

In [35]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [36]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [37]:
ar.flat

In [38]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [39]:
ar.ndim

2

In [40]:
ar.size

9

In [41]:
ar.nbytes

36

In [42]:
# without parenthesis when we apply some method it is attribute and with parenthesis they are functions
one = np.array([8,2,3,9,5,7])

In [43]:
# argmax - gives the index of greatest element 
one.argmax()

3

In [44]:
# argmin - gives the index of smallest element
one.argmin()

1

In [45]:
# argsort - gives the index of elements if arranged in ascending order
one.argsort()

array([1, 2, 4, 5, 0, 3], dtype=int64)

In [46]:
# for 2-d array
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [47]:
ar.argmin()

8

In [48]:
ar.argmax()

6

In [49]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [50]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [51]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [52]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [53]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [54]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [55]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [56]:
ar.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [57]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [58]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [59]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [60]:
ar *ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [61]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [62]:
ar.sum()

29

In [63]:
ar.max()

7

In [64]:
ar.min()

0

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [67]:
type(np.where(ar>5))

tuple

In [68]:
np.count_nonzero(ar)

8

In [69]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [70]:
ar[1,2]=0

In [71]:
# For each axis we get a indices where we get a nonzero element
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [72]:
import sys

In [73]:
py_ar = [0,4,55,2]
np_ar = np.array(py_ar)

In [74]:
sys.getsizeof(1)*len(py_ar)

112

In [75]:
np_ar.itemsize*np_ar.size

16

In [76]:
# converting numpy array to python list
np_ar.tolist()

[0, 4, 55, 2]

In [77]:
#Python buffer object pointing to the start of the array’s data.
ar.data

In [78]:
#Information about the memory layout of the array.
"""
Only the UPDATEIFCOPY, WRITEABLE, and ALIGNED flags can be changed by the user, via direct assignment to the attribute or dictionary entry, or by calling ndarray.setflags.
The array flags cannot be set arbitrarily:
UPDATEIFCOPY can only be set False.
ALIGNED can only be set True if the data is truly aligned.
WRITEABLE can only be set True if the array owns its own memory or the ultimate owner of the memory exposes a writeable buffer interface or is a string.
"""
ar.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [79]:
# flat
#A 1-D iterator over the array.-Return a copy of the array collapsed into one dimension.
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
x.flat[3]

4

In [81]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [82]:
x.T.flat[3]

5

In [83]:
type(x.flat)

numpy.flatiter

In [84]:
# imag(val)-Return the imaginary part of the elements of the array.
a = np.array([1+2j, 3+4j, 5+6j])
a.imag

array([2., 4., 6.])

In [85]:
a.imag = np.array([8, 10, 12])
a

array([1. +8.j, 3.+10.j, 5.+12.j])

In [86]:
# real(val)-Return the real part of the elements of the array.
a = np.array([1+2j, 3+4j, 5+6j])
a.real

array([1., 3., 5.])

In [87]:
a.real = 9

In [88]:
a.real = np.array([9, 8, 7])
a

array([9.+2.j, 8.+4.j, 7.+6.j])

In [89]:
# size(a, axis)	Return the number of elements along a given axis.
np.size(ar,axis=1)

3

In [90]:
np.size(ar,axis=None)  # total size i.e. no. of elements

9

In [91]:
# ndarray.itemsize - Length of one array element in bytes.
x = np.array([1,2,3], dtype=np.float64)
x.itemsize

8

In [92]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

In [93]:
# nbytes -Total bytes consumed by the elements of the array.
arr1 = np.zeros((1, 2, 3), dtype =np.complex128)
  
gfg = arr1.nbytes
  
print (gfg)

96


In [94]:
# all(a[, axis, out]) - Test whether all array elements along a given axis evaluate to True.
# Not a Number (NaN), positive infinity and negative infinity evaluate to True because these are not equal to zero.
np.all([[True,False],[True,True]])

False

In [95]:
np.all([[True,True],[True,True]])

True

In [96]:
np.all([[True,False],[True,True]], axis=0)

array([ True, False])

In [97]:
np.all([-1, 4, 0])

False

In [98]:
np.all([1.0, np.nan])

True

In [99]:
np.all([-1, 4, 6])

True

In [100]:
# any(a[, axis, out]) - Test whether any array element along a given axis evaluates to True.
np.any([[True, False], [True, True]])

True

In [101]:
np.any([[True, False], [False, False]], axis=0)

array([ True, False])

In [102]:
 np.any([-1, 0, 5])

True

In [103]:
 np.any(np.nan)

True

In [104]:
# ndarray.astype(dtype) - Copy of the array, cast to a specified type.
# note - When casting from complex to float or int. To avoid this, one should use a.real.astype(t).
x = np.array([1, 2, 2.5])
x

array([1. , 2. , 2.5])

In [105]:
x.astype(int)

array([1, 2, 2])

In [106]:
# numpy.clip(a, a_min, a_max, out=None) - Clip (limit) the values in an array.
a = np.arange(10)
np.clip(a, 1, 8)

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])

In [107]:
np.clip(a, 3, 6, out=a)

array([3, 3, 3, 3, 4, 5, 6, 6, 6, 6])

In [108]:
a = np.arange(10)

In [109]:
np.clip(a, [3,4,1,1,1,4,4,4,4,4], 8)

array([3, 4, 2, 3, 4, 5, 6, 7, 8, 8])

In [110]:
# numpy.compress(condition, a, axis=None, out=None) - Return selected slices of an array along given axis.
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [111]:
np.compress([1,0,0], a, axis=0)

array([[1, 2]])

In [112]:
 np.compress([False, True, True], a, axis=0)

array([[3, 4],
       [5, 6]])

In [113]:
np.compress([False, True], a, axis=1)

array([[2],
       [4],
       [6]])

In [114]:
np.compress([0,1,0], a, axis=0)

array([[3, 4]])

In [115]:
# numpy.conj(x[, out]) - Return the complex conjugate, element-wise.
np.conjugate(1+2j)

(1-2j)

In [116]:
# eye() function in Python is used to return a two-dimensional array with ones (1) on the diagonal and zeros (0) elsewhere.
x = np.eye(2) + 1j * np.eye(2)
np.conjugate(x)

array([[1.-1.j, 0.-0.j],
       [0.-0.j, 1.-1.j]])

In [117]:
# numpy.copy(a) - Return an array copy of the given object.
x = np.array([1, 2, 3])
y = x
z = np.copy(x)

In [118]:
x[0] = 10
x[0] == y[0]

True

In [119]:
#Note that, when we modify x, y changes, but not z:
x[0] == z[0]

False

In [120]:
# numpy.cumprod(a, axis=None, dtype=None, out=None) - Return the cumulative product of elements along a given axis.
a = np.array([1,2,3])
np.cumprod(a) # intermediate results 1, 1*2             # total product 1*2*3 = 6

array([1, 2, 6], dtype=int32)

In [121]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.cumprod(a, dtype=float) # specify type of output

array([  1.,   2.,   6.,  24., 120., 720.])

In [122]:
# numpy.cumsum(a, axis=None, dtype=None, out=None) - Return the cumulative sum of the elements along a given axis.
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [124]:
np.cumsum(a, dtype=float)     # specifies type of output value(s)

array([ 1.,  3.,  6., 10., 15., 21.])

In [125]:
np.cumsum(a,axis=0)      # sum over rows for each of the 3 columns

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [126]:
np.cumsum(a,axis=1)      # sum over columns for each of the 2 rows

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [127]:
# numpy.diagonal(a, offset=0, axis1=0, axis2=1) - Return specified diagonals.
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [128]:
a.diagonal()

array([0, 3])

In [129]:
a.diagonal(1)

array([1])

In [130]:
# A 3-D example:
a = np.arange(8).reshape(2,2,2); 
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [131]:
 a.diagonal(0, # Main diagonals of two arrays created by skipping
            0, # across the outer(left)-most axis last and
            1) # the "middle" (row) axis first.

array([[0, 6],
       [1, 7]])

In [132]:
# The sub-arrays whose main diagonals we just obtained; note that each corresponds to fixing the right-most (column) axis, and that the diagonals are “packed” in rows.
a[:,:,0] # main diagonal is [0 6]

array([[0, 2],
       [4, 6]])

In [133]:
a[:,:,1] # main diagonal is [1 7]

array([[1, 3],
       [5, 7]])

In [134]:
# numpy.dot(a, b, out=None) - gives dot product of two arrays
np.dot(3, 4)

12

In [135]:
 np.dot([2j, 3j], [2j, 3j])

(-13+0j)

In [136]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [137]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
##### np.dot(a, b)[2,3,2,1,2,2]

In [138]:
#### sum(a[2,3,2,:] * b[1,2,:,2])

In [139]:
# ndarray.dump(file) - Dump a pickle of the array to the specified file. The array can be read back with pickle.load or numpy.load.

In [140]:
# ndarray.fill(value) - Fill the array with a scalar value.
a = np.array([1, 2])
a.fill(0)
a

array([0, 0])

In [141]:
a = np.empty(2)
a.fill(1)
a

array([1., 1.])

In [142]:
# ndarray.flatten(order='C')-Return a copy of the array collapsed into one dimension.
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

In [143]:
a.flatten('F')

array([1, 3, 2, 4])

In [144]:
# ndarray.getfield(dtype, offset) -Returns a field of the given array as a certain type.
x= np.diag([1.+1.j]*2)
x

array([[1.+1.j, 0.+0.j],
       [0.+0.j, 1.+1.j]])

In [145]:
x.dtype

dtype('complex128')

In [146]:
x.getfield('complex64',0) # note how this != x

array([[0.+1.875j, 0.+0.j   ],
       [0.+0.j   , 0.+1.875j]], dtype=complex64)

In [147]:
x.getfield('complex64',1) # Note how different this is than x

array([[0.+5.871732e-39j, 0.+0.000000e+00j],
       [0.+0.000000e+00j, 0.+5.871732e-39j]], dtype=complex64)

In [148]:
 x.getfield('complex128', 0) # == x

array([[1.+1.j, 0.+0.j],
       [0.+0.j, 1.+1.j]])

In [149]:
 #x.getfield('complex128', 1) # If the argument dtype is the same as x.dtype, then offset != 0 raises a ValueError:

In [150]:
 x.getfield('float64', 0)

array([[1., 0.],
       [0., 1.]])

In [151]:
x.getfield('float64', 1)

array([[1.77658241e-307, 0.00000000e+000],
       [0.00000000e+000, 1.77658241e-307]])

In [152]:
# ndarray.item(*args) - Copy an element of an array to a standard Python scalar and return it.
x = np.random.randint(9,size=(3,3))
x

array([[3, 3, 5],
       [2, 0, 1],
       [8, 4, 2]])

In [153]:
x.item(3)

2

In [154]:
x.item(1,2)

1

In [155]:
x.item(2,2)

2

In [156]:
# max(a[, axis, out]) - Return the maximum of an array or maximum along an axis.
max(np.arange(9))

8

In [157]:
# min(a[, axis, out])	Return the minimum of an array or minimum along an axis.

In [158]:
# numpy.mean(a, axis=None, dtype=None, out=None) - 
a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

In [159]:
np.mean(a, axis=0)

array([2., 3.])

In [160]:
np.mean(a,axis=1)

array([1.5, 3.5])

In [161]:
a = np.zeros((2, 512*512), dtype=np.float32)
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [162]:
# In single precision, mean can be inaccurate:
a[0, :] = 1.0
a[1, :] = 0.1

In [163]:
a

array([[1. , 1. , 1. , ..., 1. , 1. , 1. ],
       [0.1, 0.1, 0.1, ..., 0.1, 0.1, 0.1]], dtype=float32)

In [164]:
np.mean(a)

0.54999924

In [165]:
# Computing the mean in float64 is more accurate:

np.mean(a, dtype=np.float64)

0.5500000007450581

In [166]:
# numpy.nonzero(a)-Return the indices of the elements that are non-zero.
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [167]:
np.nonzero(x)

(array([0, 1, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [168]:
 x[np.nonzero(x)]

array([1., 1., 1.])

In [169]:
# A common use for nonzero is to find the indices of an array, where a condition is True. Given an array a, 
#the condition a > 3 is a boolean array and since False is interpreted as 0, np.nonzero(a > 3) 
# yields the indices of the a where the condition is true.
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [170]:
a>3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [171]:
np.nonzero(a>3)

(array([1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [172]:
# The nonzero method of the boolean array can also be called.
(a > 3).nonzero()

(array([1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [173]:
# numpy.prod(a, axis=None, dtype=None, out=None) - Return the product of array elements over a given axis.
#### NOTE =arithmetic is modular when using integer types, and no error is raised on overflow. That means that, on a 32-bit platform:
x = np.array([536870910, 536870910, 536870910, 536870910])
np.prod(x) #random

16

In [174]:
 np.prod([1.,2.])

2.0

In [175]:
# Even when the input array is two-dimensional:
np.prod([[1.,2.],[3.,4.]])

24.0

In [176]:
# But we can also specify the axis over which to multiply:
np.prod([[1.,2.],[3.,4.]], axis=1)

array([ 2., 12.])

In [177]:
# If the type of x is unsigned, then the output type is the unsigned platform integer:
x = np.array([1, 2, 3], dtype=np.uint8)
np.prod(x).dtype == np.uint

True

In [178]:
# If x is of a signed integer type, then the output type is the default platform integer:
x = np.array([1, 2, 3], dtype=np.int8)
np.prod(x).dtype == np.int

C:\Users\chait\AppData\Local\Temp\ipykernel_20600\785933626.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.prod(x).dtype == np.int


True

In [179]:
# numpy.put(a, ind, v, mode='raise') - Replaces specified elements of an array with given values.
a = np.arange(5)
np.put(a, [0, 2], [-44, -55])
a

array([-44,   1, -55,   3,   4])

In [180]:
"""
mode : {‘raise’, ‘wrap’, ‘clip’}, optional
Specifies how out-of-bounds indices will behave.
‘raise’ – raise an error (default)
‘wrap’ – wrap around
‘clip’ – clip to the range
‘clip’ mode means that all indices that are too large are replaced by the index that addresses the last element along that axis.
Note that this disables indexing with negative numbers.
"""
a = np.arange(5)
np.put(a, 22, -5, mode='clip')
a

array([ 0,  1,  2,  3, -5])

In [181]:
# numpy.repeat(a, repeats, axis=None) - Repeat elements of an array.
x = np.array([[1,2],[3,4]])
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [182]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [183]:
np.repeat(x, [1, 2], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])